[2025-05-14T22:53:28.504+0000] {processor.py:157} INFO - Started process (PID=9197) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:53:28.504+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T22:53:28.505+0000] {logging_mixin.py:154} INFO - [2025-05-14T22:53:28.505+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:53:28.630+0000] {logging_mixin.py:154} INFO - [2025-05-14T22:53:28.626+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T22:53:28.630+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:53:28.641+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.140 seconds
[2025-05-14T22:53:58.967+0000] {processor.py:157} INFO - Started process (PID=9219) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:53:58.969+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T22:53:58.970+0000] {logging_mixin.py:154} INFO - [2025-05-14T22:53:58.969+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:53:59.122+0000] {logging_mixin.py:154} INFO - [2025-05-14T22:53:59.120+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T22:53:59.123+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:53:59.133+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.171 seconds
[2025-05-14T22:54:29.355+0000] {processor.py:157} INFO - Started process (PID=9241) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:54:29.355+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T22:54:29.356+0000] {logging_mixin.py:154} INFO - [2025-05-14T22:54:29.356+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:54:29.482+0000] {logging_mixin.py:154} INFO - [2025-05-14T22:54:29.480+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T22:54:29.482+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:54:29.491+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.139 seconds
[2025-05-14T22:54:59.817+0000] {processor.py:157} INFO - Started process (PID=9263) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:54:59.819+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T22:54:59.820+0000] {logging_mixin.py:154} INFO - [2025-05-14T22:54:59.819+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:54:59.955+0000] {logging_mixin.py:154} INFO - [2025-05-14T22:54:59.954+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T22:54:59.956+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:54:59.964+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.152 seconds
[2025-05-14T22:55:30.320+0000] {processor.py:157} INFO - Started process (PID=9285) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:55:30.321+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T22:55:30.322+0000] {logging_mixin.py:154} INFO - [2025-05-14T22:55:30.321+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:55:30.461+0000] {logging_mixin.py:154} INFO - [2025-05-14T22:55:30.459+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T22:55:30.461+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:55:30.471+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.157 seconds
[2025-05-14T22:56:08.438+0000] {processor.py:157} INFO - Started process (PID=165) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:56:08.439+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T22:56:08.440+0000] {logging_mixin.py:154} INFO - [2025-05-14T22:56:08.440+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:56:09.086+0000] {logging_mixin.py:154} INFO - [2025-05-14T22:56:09.085+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T22:56:09.086+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:56:09.096+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.661 seconds
[2025-05-14T22:56:39.521+0000] {processor.py:157} INFO - Started process (PID=188) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:56:39.523+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T22:56:39.524+0000] {logging_mixin.py:154} INFO - [2025-05-14T22:56:39.524+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:56:39.839+0000] {logging_mixin.py:154} INFO - [2025-05-14T22:56:39.838+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T22:56:39.839+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:56:39.849+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.337 seconds
[2025-05-14T22:56:55.112+0000] {processor.py:157} INFO - Started process (PID=210) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:56:55.114+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T22:56:55.115+0000] {logging_mixin.py:154} INFO - [2025-05-14T22:56:55.115+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:56:55.344+0000] {logging_mixin.py:154} INFO - [2025-05-14T22:56:55.343+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T22:56:55.345+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:56:55.353+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.245 seconds
[2025-05-14T22:57:25.627+0000] {processor.py:157} INFO - Started process (PID=232) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:57:25.629+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T22:57:25.630+0000] {logging_mixin.py:154} INFO - [2025-05-14T22:57:25.630+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:57:25.863+0000] {logging_mixin.py:154} INFO - [2025-05-14T22:57:25.861+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T22:57:25.863+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:57:25.871+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.255 seconds
[2025-05-14T22:57:57.090+0000] {processor.py:157} INFO - Started process (PID=166) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:57:57.091+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T22:57:57.092+0000] {logging_mixin.py:154} INFO - [2025-05-14T22:57:57.091+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:57:57.736+0000] {logging_mixin.py:154} INFO - [2025-05-14T22:57:57.734+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T22:57:57.736+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:57:57.747+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.660 seconds
[2025-05-14T22:58:28.249+0000] {processor.py:157} INFO - Started process (PID=188) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:58:28.250+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T22:58:28.250+0000] {logging_mixin.py:154} INFO - [2025-05-14T22:58:28.250+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:58:28.512+0000] {logging_mixin.py:154} INFO - [2025-05-14T22:58:28.510+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T22:58:28.512+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:58:28.521+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.275 seconds
[2025-05-14T22:58:56.922+0000] {processor.py:157} INFO - Started process (PID=210) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:58:56.927+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T22:58:56.929+0000] {logging_mixin.py:154} INFO - [2025-05-14T22:58:56.929+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:58:57.264+0000] {logging_mixin.py:154} INFO - [2025-05-14T22:58:57.262+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T22:58:57.264+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:58:57.274+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.359 seconds
[2025-05-14T22:59:27.436+0000] {processor.py:157} INFO - Started process (PID=232) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:59:27.437+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T22:59:27.439+0000] {logging_mixin.py:154} INFO - [2025-05-14T22:59:27.438+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:59:27.708+0000] {logging_mixin.py:154} INFO - [2025-05-14T22:59:27.707+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T22:59:27.708+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:59:27.717+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.287 seconds
[2025-05-14T22:59:57.997+0000] {processor.py:157} INFO - Started process (PID=254) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:59:57.999+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T22:59:58.000+0000] {logging_mixin.py:154} INFO - [2025-05-14T22:59:57.999+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:59:58.226+0000] {logging_mixin.py:154} INFO - [2025-05-14T22:59:58.225+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T22:59:58.226+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T22:59:58.234+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.242 seconds
[2025-05-14T23:00:28.502+0000] {processor.py:157} INFO - Started process (PID=276) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:00:28.503+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:00:28.504+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:00:28.503+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:00:28.704+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:00:28.703+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:00:28.704+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:00:28.712+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.212 seconds
[2025-05-14T23:00:59.058+0000] {processor.py:157} INFO - Started process (PID=298) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:00:59.059+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:00:59.060+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:00:59.060+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:00:59.379+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:00:59.378+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:00:59.380+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:00:59.390+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.337 seconds
[2025-05-14T23:01:29.534+0000] {processor.py:157} INFO - Started process (PID=320) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:01:29.535+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:01:29.536+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:01:29.536+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:01:29.761+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:01:29.760+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:01:29.762+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:01:29.771+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.241 seconds
[2025-05-14T23:02:00.141+0000] {processor.py:157} INFO - Started process (PID=342) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:02:00.142+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:02:00.143+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:02:00.143+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:02:00.414+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:02:00.413+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:02:00.415+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:02:00.425+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.291 seconds
[2025-05-14T23:02:30.617+0000] {processor.py:157} INFO - Started process (PID=364) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:02:30.618+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:02:30.620+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:02:30.619+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:02:30.863+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:02:30.862+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:02:30.863+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:02:30.871+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.260 seconds
[2025-05-14T23:03:01.271+0000] {processor.py:157} INFO - Started process (PID=386) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:03:01.272+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:03:01.273+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:03:01.273+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:03:01.487+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:03:01.486+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:03:01.487+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:03:01.496+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.230 seconds
[2025-05-14T23:03:31.838+0000] {processor.py:157} INFO - Started process (PID=408) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:03:31.839+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:03:31.840+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:03:31.839+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:03:32.132+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:03:32.130+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:03:32.132+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:03:32.148+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.313 seconds
[2025-05-14T23:04:02.324+0000] {processor.py:157} INFO - Started process (PID=430) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:04:02.325+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:04:02.325+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:04:02.325+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:04:02.558+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:04:02.557+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:04:02.558+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:04:02.566+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.244 seconds
[2025-05-14T23:04:32.778+0000] {processor.py:157} INFO - Started process (PID=452) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:04:32.779+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:04:32.780+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:04:32.780+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:04:32.985+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:04:32.984+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:04:32.986+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:04:32.993+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.218 seconds
[2025-05-14T23:05:03.349+0000] {processor.py:157} INFO - Started process (PID=474) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:05:03.350+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:05:03.351+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:05:03.350+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:05:03.579+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:05:03.578+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:05:03.580+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:05:03.588+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.245 seconds
[2025-05-14T23:05:33.948+0000] {processor.py:157} INFO - Started process (PID=496) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:05:33.950+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:05:33.951+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:05:33.950+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:05:34.172+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:05:34.171+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:05:34.172+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:05:34.180+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.237 seconds
[2025-05-14T23:06:04.428+0000] {processor.py:157} INFO - Started process (PID=518) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:06:04.429+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:06:04.430+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:06:04.429+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:06:04.644+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:06:04.643+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:06:04.645+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:06:04.653+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.228 seconds
[2025-05-14T23:06:34.977+0000] {processor.py:157} INFO - Started process (PID=540) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:06:34.978+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:06:34.979+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:06:34.979+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:06:35.206+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:06:35.205+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:06:35.206+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:06:35.215+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.242 seconds
[2025-05-14T23:07:05.437+0000] {processor.py:157} INFO - Started process (PID=562) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:07:05.438+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:07:05.439+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:07:05.439+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:07:05.689+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:07:05.688+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:07:05.690+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:07:05.698+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.266 seconds
[2025-05-14T23:07:36.014+0000] {processor.py:157} INFO - Started process (PID=584) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:07:36.015+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:07:36.016+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:07:36.016+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:07:36.262+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:07:36.260+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:07:36.262+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:07:36.271+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.261 seconds
[2025-05-14T23:08:06.519+0000] {processor.py:157} INFO - Started process (PID=606) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:08:06.520+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:08:06.522+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:08:06.521+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:08:06.728+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:08:06.727+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:08:06.729+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:08:06.737+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.224 seconds
[2025-05-14T23:08:37.079+0000] {processor.py:157} INFO - Started process (PID=628) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:08:37.080+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:08:37.081+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:08:37.081+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:08:37.288+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:08:37.287+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:08:37.288+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:08:37.295+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.220 seconds
[2025-05-14T23:09:07.571+0000] {processor.py:157} INFO - Started process (PID=650) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:09:07.572+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:09:07.573+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:09:07.572+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:09:07.785+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:09:07.784+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:09:07.785+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:09:07.793+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.225 seconds
[2025-05-14T23:09:38.143+0000] {processor.py:157} INFO - Started process (PID=672) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:09:38.144+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:09:38.146+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:09:38.145+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:09:38.462+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:09:38.461+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:09:38.462+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:09:38.473+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.339 seconds
[2025-05-14T23:10:08.647+0000] {processor.py:157} INFO - Started process (PID=694) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:10:08.648+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:10:08.649+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:10:08.649+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:10:08.861+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:10:08.859+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:10:08.861+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:10:08.869+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.226 seconds
[2025-05-14T23:10:39.244+0000] {processor.py:157} INFO - Started process (PID=716) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:10:39.245+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:10:39.246+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:10:39.246+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:10:39.488+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:10:39.487+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:10:39.489+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:10:39.498+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.260 seconds
[2025-05-14T23:11:09.747+0000] {processor.py:157} INFO - Started process (PID=738) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:11:09.748+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:11:09.749+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:11:09.748+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:11:10.017+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:11:10.016+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:11:10.017+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:11:10.026+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.284 seconds
[2025-05-14T23:11:40.360+0000] {processor.py:157} INFO - Started process (PID=760) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:11:40.361+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:11:40.362+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:11:40.362+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:11:40.577+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:11:40.576+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:11:40.577+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:11:40.584+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.229 seconds
[2025-05-14T23:12:10.837+0000] {processor.py:157} INFO - Started process (PID=782) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:12:10.837+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:12:10.838+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:12:10.838+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:12:11.039+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:12:11.038+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:12:11.039+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:12:11.047+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.214 seconds
[2025-05-14T23:12:41.364+0000] {processor.py:157} INFO - Started process (PID=804) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:12:41.365+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:12:41.366+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:12:41.366+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:12:41.575+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:12:41.574+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:12:41.575+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:12:41.583+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.224 seconds
[2025-05-14T23:13:11.960+0000] {processor.py:157} INFO - Started process (PID=826) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:13:11.961+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:13:11.962+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:13:11.962+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:13:12.202+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:13:12.201+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:13:12.202+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:13:12.212+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.258 seconds
[2025-05-14T23:13:42.479+0000] {processor.py:157} INFO - Started process (PID=848) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:13:42.480+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:13:42.481+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:13:42.481+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:13:42.722+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:13:42.721+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:13:42.722+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:13:42.731+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.258 seconds
[2025-05-14T23:14:12.975+0000] {processor.py:157} INFO - Started process (PID=870) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:14:12.976+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:14:12.976+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:14:12.976+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:14:13.238+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:14:13.237+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:14:13.239+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:14:13.248+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.277 seconds
[2025-05-14T23:14:43.482+0000] {processor.py:157} INFO - Started process (PID=892) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:14:43.483+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:14:43.484+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:14:43.484+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:14:43.704+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:14:43.703+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:14:43.704+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:14:43.712+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.236 seconds
[2025-05-14T23:15:14.054+0000] {processor.py:157} INFO - Started process (PID=914) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:15:14.055+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:15:14.056+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:15:14.055+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:15:14.307+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:15:14.306+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:15:14.308+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:15:14.316+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.267 seconds
[2025-05-14T23:15:44.619+0000] {processor.py:157} INFO - Started process (PID=936) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:15:44.620+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:15:44.621+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:15:44.621+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:15:44.858+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:15:44.857+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:15:44.859+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:15:44.867+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.255 seconds
[2025-05-14T23:16:15.173+0000] {processor.py:157} INFO - Started process (PID=958) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:16:15.174+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:16:15.175+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:16:15.175+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:16:15.436+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:16:15.435+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:16:15.437+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:16:15.446+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.279 seconds
[2025-05-14T23:16:45.682+0000] {processor.py:157} INFO - Started process (PID=980) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:16:45.683+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:16:45.683+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:16:45.683+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:16:45.920+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:16:45.919+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:16:45.920+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:16:45.929+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.251 seconds
[2025-05-14T23:17:16.227+0000] {processor.py:157} INFO - Started process (PID=1002) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:17:16.227+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:17:16.228+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:17:16.228+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:17:16.470+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:17:16.469+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:17:16.471+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:17:16.480+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.256 seconds
[2025-05-14T23:17:46.709+0000] {processor.py:157} INFO - Started process (PID=1024) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:17:46.710+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:17:46.711+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:17:46.710+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:17:46.917+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:17:46.916+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:17:46.917+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:17:46.925+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.221 seconds
[2025-05-14T23:18:17.372+0000] {processor.py:157} INFO - Started process (PID=1046) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:18:17.373+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:18:17.375+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:18:17.374+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:18:17.683+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:18:17.682+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 13, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:18:17.684+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:18:17.694+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.330 seconds
[2025-05-14T23:18:26.632+0000] {processor.py:157} INFO - Started process (PID=1068) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:18:26.634+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:18:26.635+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:18:26.634+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:18:26.645+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:18:26.643+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 16, in <module>
    from model.train_model import train_model
ModuleNotFoundError: No module named 'model'
[2025-05-14T23:18:26.645+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:18:26.665+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.039 seconds
[2025-05-14T23:18:57.157+0000] {processor.py:157} INFO - Started process (PID=1089) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:18:57.159+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:18:57.160+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:18:57.159+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:18:57.167+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:18:57.166+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 16, in <module>
    from model.train_model import train_model
ModuleNotFoundError: No module named 'model'
[2025-05-14T23:18:57.167+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:18:57.185+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.032 seconds
[2025-05-14T23:19:20.387+0000] {processor.py:157} INFO - Started process (PID=1094) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:19:20.388+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:19:20.388+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:19:20.388+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:19:20.711+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:19:20.709+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:19:20.711+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:19:20.722+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.339 seconds
[2025-05-14T23:19:51.047+0000] {processor.py:157} INFO - Started process (PID=1116) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:19:51.048+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:19:51.049+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:19:51.049+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:19:51.378+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:19:51.377+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:19:51.379+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:19:51.390+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.349 seconds
[2025-05-14T23:20:21.783+0000] {processor.py:157} INFO - Started process (PID=1138) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:20:21.784+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:20:21.785+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:20:21.785+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:20:22.026+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:20:22.025+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:20:22.026+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:20:22.035+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.258 seconds
[2025-05-14T23:20:52.462+0000] {processor.py:157} INFO - Started process (PID=1160) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:20:52.464+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:20:52.465+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:20:52.464+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:20:52.689+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:20:52.688+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:20:52.690+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:20:52.697+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.240 seconds
[2025-05-14T23:21:23.105+0000] {processor.py:157} INFO - Started process (PID=1182) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:21:23.107+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:21:23.107+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:21:23.107+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:21:23.365+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:21:23.364+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:21:23.365+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:21:23.374+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.273 seconds
[2025-05-14T23:21:53.844+0000] {processor.py:157} INFO - Started process (PID=1204) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:21:53.845+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:21:53.847+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:21:53.846+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:21:54.128+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:21:54.127+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:21:54.129+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:21:54.138+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.302 seconds
[2025-05-14T23:22:09.777+0000] {processor.py:157} INFO - Started process (PID=166) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:22:09.778+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:22:09.778+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:22:09.778+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:22:10.465+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:22:10.463+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:22:10.465+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:22:10.477+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.702 seconds
[2025-05-14T23:22:40.946+0000] {processor.py:157} INFO - Started process (PID=188) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:22:40.948+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:22:40.949+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:22:40.948+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:22:41.270+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:22:41.269+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:22:41.270+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:22:41.279+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.337 seconds
[2025-05-14T23:23:11.717+0000] {processor.py:157} INFO - Started process (PID=210) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:23:11.718+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:23:11.720+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:23:11.719+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:23:11.995+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:23:11.994+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:23:11.996+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:23:12.008+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.297 seconds
[2025-05-14T23:23:42.478+0000] {processor.py:157} INFO - Started process (PID=232) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:23:42.480+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:23:42.481+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:23:42.481+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:23:42.753+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:23:42.751+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:23:42.753+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:23:42.762+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.291 seconds
[2025-05-14T23:24:13.229+0000] {processor.py:157} INFO - Started process (PID=254) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:24:13.230+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:24:13.232+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:24:13.232+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:24:13.467+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:24:13.466+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:24:13.467+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:24:13.476+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.253 seconds
[2025-05-14T23:24:43.962+0000] {processor.py:157} INFO - Started process (PID=276) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:24:43.963+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:24:43.964+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:24:43.964+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:24:44.185+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:24:44.184+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:24:44.186+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:24:44.194+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.237 seconds
[2025-05-14T23:25:14.594+0000] {processor.py:157} INFO - Started process (PID=298) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:25:14.595+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:25:14.596+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:25:14.596+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:25:14.830+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:25:14.829+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:25:14.830+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:25:14.838+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.247 seconds
[2025-05-14T23:25:45.324+0000] {processor.py:157} INFO - Started process (PID=320) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:25:45.326+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:25:45.327+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:25:45.327+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:25:45.558+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:25:45.557+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:25:45.559+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:25:45.567+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.249 seconds
[2025-05-14T23:26:16.051+0000] {processor.py:157} INFO - Started process (PID=342) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:26:16.052+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:26:16.053+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:26:16.053+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:26:16.280+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:26:16.279+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:26:16.281+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:26:16.288+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.243 seconds
[2025-05-14T23:26:46.731+0000] {processor.py:157} INFO - Started process (PID=364) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:26:46.733+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:26:46.734+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:26:46.733+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:26:47.007+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:26:47.006+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:26:47.007+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:26:47.017+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.294 seconds
[2025-05-14T23:27:17.497+0000] {processor.py:157} INFO - Started process (PID=386) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:27:17.499+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:27:17.500+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:27:17.500+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:27:17.787+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:27:17.786+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:27:17.787+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:27:17.796+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.305 seconds
[2025-05-14T23:27:48.226+0000] {processor.py:157} INFO - Started process (PID=408) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:27:48.228+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:27:48.229+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:27:48.229+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:27:48.452+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:27:48.451+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:27:48.453+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:27:48.461+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.240 seconds
[2025-05-14T23:28:18.956+0000] {processor.py:157} INFO - Started process (PID=430) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:28:18.957+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:28:18.959+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:28:18.959+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:28:19.315+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:28:19.313+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:28:19.315+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:28:19.327+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.380 seconds
[2025-05-14T23:28:49.707+0000] {processor.py:157} INFO - Started process (PID=452) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:28:49.708+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:28:49.709+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:28:49.708+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:28:49.974+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:28:49.972+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:28:49.974+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:28:49.984+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.279 seconds
[2025-05-14T23:29:20.365+0000] {processor.py:157} INFO - Started process (PID=474) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:29:20.366+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:29:20.367+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:29:20.367+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:29:20.632+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:29:20.630+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:29:20.632+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:29:20.642+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.284 seconds
[2025-05-14T23:29:51.049+0000] {processor.py:157} INFO - Started process (PID=496) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:29:51.050+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:29:51.051+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:29:51.051+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:29:51.275+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:29:51.274+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:29:51.276+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:29:51.283+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.240 seconds
[2025-05-14T23:30:21.735+0000] {processor.py:157} INFO - Started process (PID=518) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:30:21.737+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:30:21.738+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:30:21.738+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:30:22.028+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:30:22.026+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:30:22.028+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:30:22.037+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.310 seconds
[2025-05-14T23:30:52.492+0000] {processor.py:157} INFO - Started process (PID=540) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:30:52.493+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:30:52.495+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:30:52.494+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:30:52.776+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:30:52.774+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:30:52.776+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:30:52.785+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.300 seconds
[2025-05-14T23:31:23.187+0000] {processor.py:157} INFO - Started process (PID=562) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:31:23.189+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:31:23.190+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:31:23.190+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:31:23.423+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:31:23.422+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:31:23.423+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:31:23.431+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.249 seconds
[2025-05-14T23:31:53.812+0000] {processor.py:157} INFO - Started process (PID=584) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:31:53.813+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:31:53.814+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:31:53.814+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:31:54.039+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:31:54.038+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:31:54.040+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:31:54.049+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.241 seconds
[2025-05-14T23:32:24.509+0000] {processor.py:157} INFO - Started process (PID=606) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:32:24.511+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:32:24.512+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:32:24.511+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:32:24.866+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:32:24.865+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:32:24.866+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:32:24.878+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.377 seconds
[2025-05-14T23:32:55.284+0000] {processor.py:157} INFO - Started process (PID=628) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:32:55.285+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:32:55.286+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:32:55.285+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:32:55.505+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:32:55.504+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:32:55.505+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:32:55.515+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.234 seconds
[2025-05-14T23:33:25.928+0000] {processor.py:157} INFO - Started process (PID=650) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:33:25.929+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:33:25.930+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:33:25.930+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:33:26.157+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:33:26.155+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:33:26.157+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:33:26.165+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.241 seconds
[2025-05-14T23:33:56.537+0000] {processor.py:157} INFO - Started process (PID=672) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:33:56.539+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:33:56.541+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:33:56.540+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:33:56.766+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:33:56.765+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:33:56.767+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:33:56.775+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.244 seconds
[2025-05-14T23:34:27.210+0000] {processor.py:157} INFO - Started process (PID=694) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:34:27.211+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:34:27.213+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:34:27.212+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:34:27.587+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:34:27.585+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:34:27.587+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:34:27.599+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.406 seconds
[2025-05-14T23:34:58.049+0000] {processor.py:157} INFO - Started process (PID=716) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:34:58.051+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:34:58.052+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:34:58.052+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:34:58.282+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:34:58.281+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:34:58.282+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:34:58.291+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.248 seconds
[2025-05-14T23:35:28.766+0000] {processor.py:157} INFO - Started process (PID=738) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:35:28.768+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:35:28.769+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:35:28.769+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:35:29.032+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:35:29.031+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:35:29.032+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:35:29.041+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.285 seconds
[2025-05-14T23:35:59.397+0000] {processor.py:157} INFO - Started process (PID=760) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:35:59.398+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:35:59.399+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:35:59.399+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:35:59.722+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:35:59.720+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:35:59.722+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:35:59.740+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.347 seconds
[2025-05-14T23:36:30.177+0000] {processor.py:157} INFO - Started process (PID=782) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:36:30.178+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:36:30.178+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:36:30.178+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:36:30.408+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:36:30.407+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:36:30.408+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:36:30.418+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.245 seconds
[2025-05-14T23:37:00.834+0000] {processor.py:157} INFO - Started process (PID=804) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:37:00.835+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:37:00.835+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:37:00.835+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:37:01.061+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:37:01.060+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:37:01.061+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:37:01.070+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.239 seconds
[2025-05-14T23:37:24.613+0000] {processor.py:157} INFO - Started process (PID=165) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:37:24.614+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:37:24.615+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:37:24.615+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:37:25.263+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:37:25.262+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:37:25.263+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:37:25.288+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.676 seconds
[2025-05-14T23:37:55.672+0000] {processor.py:157} INFO - Started process (PID=187) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:37:55.675+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:37:55.679+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:37:55.677+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:37:56.028+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:37:56.027+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:37:56.028+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:37:56.038+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.377 seconds
[2025-05-14T23:38:26.372+0000] {processor.py:157} INFO - Started process (PID=209) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:38:26.373+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:38:26.374+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:38:26.374+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:38:26.709+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:38:26.707+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:38:26.709+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:38:26.718+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.353 seconds
[2025-05-14T23:38:57.187+0000] {processor.py:157} INFO - Started process (PID=231) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:38:57.189+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:38:57.191+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:38:57.190+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:38:57.499+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:38:57.498+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:38:57.499+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:38:57.507+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.332 seconds
[2025-05-14T23:39:27.974+0000] {processor.py:157} INFO - Started process (PID=253) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:39:27.977+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:39:27.979+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:39:27.979+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:39:28.241+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:39:28.236+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:39:28.242+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:39:28.257+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.290 seconds
[2025-05-14T23:39:58.751+0000] {processor.py:157} INFO - Started process (PID=275) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:39:58.753+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:39:58.754+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:39:58.754+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:39:59.001+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:39:59.000+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:39:59.002+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:39:59.010+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.266 seconds
[2025-05-14T23:40:29.411+0000] {processor.py:157} INFO - Started process (PID=297) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:40:29.412+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:40:29.413+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:40:29.413+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:40:29.664+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:40:29.663+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:40:29.665+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:40:29.673+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.267 seconds
[2025-05-14T23:41:00.191+0000] {processor.py:157} INFO - Started process (PID=319) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:41:00.193+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:41:00.194+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:41:00.194+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:41:00.466+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:41:00.465+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:41:00.466+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:41:00.475+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.291 seconds
[2025-05-14T23:41:30.933+0000] {processor.py:157} INFO - Started process (PID=341) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:41:30.934+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:41:30.936+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:41:30.935+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:41:31.166+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:41:31.165+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:41:31.167+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:41:31.174+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.247 seconds
[2025-05-14T23:42:01.620+0000] {processor.py:157} INFO - Started process (PID=363) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:42:01.621+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:42:01.623+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:42:01.622+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:42:01.849+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:42:01.848+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:42:01.850+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:42:01.858+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.245 seconds
[2025-05-14T23:42:32.371+0000] {processor.py:157} INFO - Started process (PID=385) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:42:32.373+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:42:32.374+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:42:32.374+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:42:32.608+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:42:32.607+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:42:32.608+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:42:32.616+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.250 seconds
[2025-05-14T23:43:03.047+0000] {processor.py:157} INFO - Started process (PID=407) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:43:03.048+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:43:03.049+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:43:03.049+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:43:03.273+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:43:03.272+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:43:03.274+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:43:03.282+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.240 seconds
[2025-05-14T23:43:33.781+0000] {processor.py:157} INFO - Started process (PID=429) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:43:33.782+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:43:33.784+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:43:33.783+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:43:34.018+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:43:34.017+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:43:34.019+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:43:34.027+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.252 seconds
[2025-05-14T23:44:04.539+0000] {processor.py:157} INFO - Started process (PID=451) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:44:04.540+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:44:04.542+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:44:04.541+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:44:04.799+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:44:04.798+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:44:04.800+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:44:04.808+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.277 seconds
[2025-05-14T23:44:35.348+0000] {processor.py:157} INFO - Started process (PID=473) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:44:35.350+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:44:35.352+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:44:35.351+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:44:35.608+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:44:35.607+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:44:35.608+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:44:35.616+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.276 seconds
[2025-05-14T23:45:06.117+0000] {processor.py:157} INFO - Started process (PID=495) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:45:06.118+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:45:06.120+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:45:06.119+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:45:06.359+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:45:06.358+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:45:06.359+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:45:06.367+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.257 seconds
[2025-05-14T23:45:36.944+0000] {processor.py:157} INFO - Started process (PID=517) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:45:36.946+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:45:36.948+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:45:36.947+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:45:37.285+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:45:37.283+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:45:37.285+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:45:37.296+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.363 seconds
[2025-05-14T23:46:07.808+0000] {processor.py:157} INFO - Started process (PID=539) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:46:07.810+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:46:07.811+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:46:07.811+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:46:08.052+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:46:08.051+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:46:08.052+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:46:08.060+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.258 seconds
[2025-05-14T23:46:38.533+0000] {processor.py:157} INFO - Started process (PID=561) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:46:38.534+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:46:38.535+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:46:38.535+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:46:38.763+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:46:38.762+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:46:38.764+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:46:38.772+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.244 seconds
[2025-05-14T23:47:09.277+0000] {processor.py:157} INFO - Started process (PID=583) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:47:09.278+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:47:09.279+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:47:09.279+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:47:09.504+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:47:09.503+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:47:09.504+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:47:09.513+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.239 seconds
[2025-05-14T23:47:40.036+0000] {processor.py:157} INFO - Started process (PID=605) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:47:40.037+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:47:40.038+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:47:40.038+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:47:40.272+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:47:40.271+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:47:40.272+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:47:40.279+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.249 seconds
[2025-05-14T23:48:10.791+0000] {processor.py:157} INFO - Started process (PID=627) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:48:10.792+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:48:10.793+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:48:10.793+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:48:11.020+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:48:11.019+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:48:11.020+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:48:11.028+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.242 seconds
[2025-05-14T23:48:41.494+0000] {processor.py:157} INFO - Started process (PID=649) to work on /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:48:41.496+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/train_and_upload_model.py for tasks to queue
[2025-05-14T23:48:41.497+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:48:41.497+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:48:41.725+0000] {logging_mixin.py:154} INFO - [2025-05-14T23:48:41.724+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/train_and_upload_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/train_and_upload_model.py", line 15, in <module>
    from model.train_model import train_model
  File "/opt/airflow/src/model/train_model.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-05-14T23:48:41.725+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/train_and_upload_model.py
[2025-05-14T23:48:41.732+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/train_and_upload_model.py took 0.243 seconds
